export const REPORT_TYPES = [
  'sales',
  'orders',
  'inventory',
  'stock-movements',
  'ingredient-consumption',
  'wastage',
  'kitchen-performance',
  'reservations',
  'customers',
  'payments',
  'suppliers',
  'purchase-orders',
  'goods-receiving',
  'purchase-returns',
  'supplier-payments',
  'employees',
  'attendance',
  'shifts',
  'staff-performance',
  'payroll-export',
] as const;

export type ReportType = (typeof REPORT_TYPES)[number];

/** Report types gated behind the additional `staff-reports` permission, on top of the baseline `reports.view`. */
export const STAFF_REPORT_TYPES: ReportType[] = [
  'employees',
  'attendance',
  'shifts',
  'staff-performance',
  'payroll-export',
];

export interface ReportColumn {
  key: string;
  header: string;
}

/** Single source of truth for column headers, used by both the on-screen table and the CSV/Excel/PDF exporters. */
export const REPORT_COLUMNS: Record<ReportType, ReportColumn[]> = {
  sales: [
    { key: 'orderNumber', header: 'Order #' },
    { key: 'createdAt', header: 'Date' },
    { key: 'subtotal', header: 'Subtotal' },
    { key: 'discountAmount', header: 'Discount' },
    { key: 'taxAmount', header: 'Tax' },
    { key: 'serviceChargeAmount', header: 'Service Charge' },
    { key: 'grandTotal', header: 'Grand Total' },
    { key: 'paymentStatus', header: 'Payment Status' },
  ],
  orders: [
    { key: 'orderNumber', header: 'Order #' },
    { key: 'createdAt', header: 'Date' },
    { key: 'orderType', header: 'Type' },
    { key: 'source', header: 'Source' },
    { key: 'status', header: 'Status' },
    { key: 'itemCount', header: 'Items' },
  ],
  inventory: [
    { key: 'ingredientName', header: 'Ingredient' },
    { key: 'warehouseName', header: 'Warehouse' },
    { key: 'quantity', header: 'On Hand' },
    { key: 'reorderLevel', header: 'Reorder Level' },
    { key: 'minimumStock', header: 'Minimum Stock' },
    { key: 'stockValue', header: 'Stock Value' },
  ],
  'stock-movements': [
    { key: 'movementType', header: 'Type' },
    { key: 'documentNo', header: 'Document #' },
    { key: 'date', header: 'Date' },
    { key: 'warehouseName', header: 'Warehouse' },
    { key: 'status', header: 'Status' },
  ],
  'ingredient-consumption': [
    { key: 'ingredientName', header: 'Ingredient' },
    { key: 'totalConsumed', header: 'Consumed' },
    { key: 'orderCount', header: 'Orders' },
  ],
  wastage: [
    { key: 'wastageDate', header: 'Date' },
    { key: 'ingredientName', header: 'Ingredient' },
    { key: 'warehouseName', header: 'Warehouse' },
    { key: 'quantity', header: 'Quantity' },
    { key: 'unitCost', header: 'Unit Cost' },
    { key: 'totalCost', header: 'Total Cost' },
    { key: 'reason', header: 'Reason' },
  ],
  'kitchen-performance': [
    { key: 'ticketId', header: 'Ticket #' },
    { key: 'orderNumber', header: 'Order #' },
    { key: 'departmentName', header: 'Station' },
    { key: 'priority', header: 'Priority' },
    { key: 'createdAt', header: 'Sent' },
    { key: 'prepMinutes', header: 'Prep Minutes' },
    { key: 'recallCount', header: 'Recalls' },
  ],
  reservations: [
    { key: 'reservedAt', header: 'Reserved For' },
    { key: 'customerName', header: 'Customer' },
    { key: 'guestCount', header: 'Guests' },
    { key: 'status', header: 'Status' },
    { key: 'source', header: 'Source' },
  ],
  customers: [
    { key: 'name', header: 'Name' },
    { key: 'phone', header: 'Phone' },
    { key: 'orderCount', header: 'Orders' },
    { key: 'totalSpent', header: 'Total Spent' },
    { key: 'lastOrderAt', header: 'Last Order' },
  ],
  payments: [
    { key: 'paymentNumber', header: 'Payment #' },
    { key: 'orderNumber', header: 'Order #' },
    { key: 'method', header: 'Method' },
    { key: 'type', header: 'Type' },
    { key: 'amount', header: 'Amount' },
    { key: 'status', header: 'Status' },
    { key: 'paidAt', header: 'Paid At' },
  ],
  suppliers: [
    { key: 'supplierNo', header: 'Supplier #' },
    { key: 'companyName', header: 'Company' },
    { key: 'contactPerson', header: 'Contact' },
    { key: 'phone', header: 'Phone' },
    { key: 'status', header: 'Status' },
    { key: 'outstandingBalance', header: 'Outstanding Balance' },
    { key: 'creditLimit', header: 'Credit Limit' },
  ],
  'purchase-orders': [
    { key: 'poNo', header: 'PO #' },
    { key: 'supplierName', header: 'Supplier' },
    { key: 'outletName', header: 'Outlet' },
    { key: 'status', header: 'Status' },
    { key: 'expectedDeliveryDate', header: 'Expected Delivery' },
    { key: 'grandTotal', header: 'Grand Total' },
    { key: 'createdAt', header: 'Created' },
  ],
  'goods-receiving': [
    { key: 'grnNo', header: 'GRN #' },
    { key: 'poNo', header: 'PO #' },
    { key: 'supplierName', header: 'Supplier' },
    { key: 'warehouseName', header: 'Warehouse' },
    { key: 'receivedDate', header: 'Received Date' },
    { key: 'status', header: 'Status' },
  ],
  'purchase-returns': [
    { key: 'returnNo', header: 'Return #' },
    { key: 'supplierName', header: 'Supplier' },
    { key: 'returnDate', header: 'Return Date' },
    { key: 'refundType', header: 'Refund Type' },
    { key: 'status', header: 'Status' },
    { key: 'totalCost', header: 'Total Cost' },
  ],
  'supplier-payments': [
    { key: 'paymentNo', header: 'Payment #' },
    { key: 'supplierName', header: 'Supplier' },
    { key: 'amount', header: 'Amount' },
    { key: 'paymentMethod', header: 'Method' },
    { key: 'status', header: 'Status' },
    { key: 'createdAt', header: 'Date' },
  ],
  employees: [
    { key: 'employeeCode', header: 'Employee #' },
    { key: 'name', header: 'Name' },
    { key: 'positionName', header: 'Position' },
    { key: 'outletName', header: 'Outlet' },
    { key: 'employmentStatus', header: 'Status' },
    { key: 'joiningDate', header: 'Joined' },
  ],
  attendance: [
    { key: 'employeeName', header: 'Employee' },
    { key: 'outletName', header: 'Outlet' },
    { key: 'clockIn', header: 'Clock In' },
    { key: 'clockOut', header: 'Clock Out' },
    { key: 'status', header: 'Status' },
    { key: 'lateMinutes', header: 'Late Minutes' },
    { key: 'workingHours', header: 'Working Hours' },
  ],
  shifts: [
    { key: 'name', header: 'Shift' },
    { key: 'outletName', header: 'Outlet' },
    { key: 'startTime', header: 'Start' },
    { key: 'endTime', header: 'End' },
    { key: 'workingHours', header: 'Working Hours' },
    { key: 'assignedCount', header: 'Assigned Employees' },
  ],
  'staff-performance': [
    { key: 'employeeName', header: 'Employee' },
    { key: 'ordersServed', header: 'Orders Served' },
    { key: 'tablesServed', header: 'Tables Served' },
    { key: 'salesGenerated', header: 'Sales Generated' },
    { key: 'avgServiceMinutes', header: 'Avg Service Minutes' },
    { key: 'workingHours', header: 'Working Hours' },
    { key: 'attendancePercent', header: 'Attendance %' },
    { key: 'lateCount', header: 'Late Count' },
  ],
  'payroll-export': [
    { key: 'employeeCode', header: 'Employee #' },
    { key: 'name', header: 'Name' },
    { key: 'positionName', header: 'Position' },
    { key: 'employmentStatus', header: 'Status' },
    { key: 'presentDays', header: 'Present Days' },
    { key: 'lateDays', header: 'Late Days' },
    { key: 'workingHours', header: 'Total Working Hours' },
  ],
};
