"use client"

import { useState, type ReactNode } from "react"
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Banknote, Boxes, CircleDollarSign, ClipboardList, Group, Package, ShoppingBag, Users } from "lucide-react"
import { DateRangeFilter, type DateRange } from "@/components/date-range-filter"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { StatCard } from "@/components/stat-card"
import { useActiveOutlet } from "@/lib/outlet/active-outlet-context"
import { useAnalyticsCustomers, useAnalyticsInventory, useAnalyticsOverview, useAnalyticsProducts } from "@/hooks/use-analytics"
import type { AnalyticsParams, CustomersAnalytics, InventoryAnalytics, OverviewAnalytics, ProductsAnalytics } from "@/hooks/use-analytics"
import { usePageTitle } from "@rms/ui/use-page-title"

type Preset = "today" | "yesterday" | "7d" | "30d" | "month" | "custom"
type Tab = "overview" | "sales" | "products" | "customers" | "inventory"
const money = (v: number) => `NPR ${Math.round(v).toLocaleString()}`
const iso = (d: Date) => d.toISOString().slice(0, 10)
function presetRange(p: Preset): DateRange { const now = new Date(); const today = iso(now); if (p === "today") return { dateFrom: today, dateTo: today }; if (p === "yesterday") { const d = new Date(now); d.setDate(d.getDate() - 1); return { dateFrom: iso(d), dateTo: iso(d) } }; if (p === "month") return { dateFrom: iso(new Date(now.getFullYear(), now.getMonth(), 1)), dateTo: today }; const d = new Date(now); d.setDate(d.getDate() - (p === "7d" ? 6 : 29)); return { dateFrom: iso(d), dateTo: today } }

function QueryState({ query, children }: { query: { isLoading: boolean; isError: boolean; refetch: () => unknown }; children: ReactNode }) {
  if (query.isLoading) return <Card><CardContent className="py-12 text-center text-sm text-muted-foreground">Loading analytics…</CardContent></Card>
  if (query.isError) return <Card><CardContent className="flex flex-col items-center gap-3 py-12 text-center text-sm text-destructive"><span>Couldn’t load this analysis.</span><button className="rounded border px-3 py-1 text-foreground" onClick={() => void query.refetch()}>Retry</button></CardContent></Card>
  return <>{children}</>
}

export default function AnalyticsPage() {
  usePageTitle("Analytics")
  const { outletId, departmentId, isLoadingOutlets } = useActiveOutlet()
  const [tab, setTab] = useState<Tab>("overview"); const [preset, setPreset] = useState<Preset>("30d"); const [custom, setCustom] = useState<DateRange>(() => presetRange("30d")); const [orderSource, setOrderSource] = useState("all"); const [orderType, setOrderType] = useState("all")
  const range = preset === "custom" ? custom : presetRange(preset)
  const params: AnalyticsParams = { outletId, departmentId, dateFrom: range.dateFrom, dateTo: range.dateTo, orderSource: orderSource === "all" ? undefined : orderSource, orderType: orderType === "all" ? undefined : orderType }
  const enabled = !isLoadingOutlets
  const overview = useAnalyticsOverview(params, { enabled })
  const products = useAnalyticsProducts(params, { enabled: enabled && tab === "products" })
  const customers = useAnalyticsCustomers(params, { enabled: enabled && tab === "customers" })
  const inventory = useAnalyticsInventory(params, { enabled: enabled && tab === "inventory" })
  const changeTab = (value: string) => { if (["overview", "sales", "products", "customers", "inventory"].includes(value)) setTab(value as Tab) }
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Analytics</h1><p className="text-sm text-muted-foreground">{range.dateFrom} — {range.dateTo}</p></div><div className="flex flex-wrap items-end gap-2"><FilterSelect label="Date range" value={preset} onChange={(v) => setPreset(v as Preset)} options={[["today", "Today"], ["yesterday", "Yesterday"], ["7d", "7D"], ["30d", "30D"], ["month", "This month"], ["custom", "Custom"]]} />{preset === "custom" && <DateRangeFilter value={custom} onChange={setCustom} />}<FilterSelect label="Order source" value={orderSource} onChange={setOrderSource} options={[["all", "All sources"], ["pos", "POS"], ["qr", "QR"], ["waiter", "Waiter"], ["online", "Online"]]} /><FilterSelect label="Order type" value={orderType} onChange={setOrderType} options={[["all", "All types"], ["table", "Table"], ["grab_and_go", "Grab & go"], ["stay", "Stay"], ["delivery", "Delivery"]]} /></div></div><Tabs value={tab} onValueChange={changeTab} orientation="vertical" className="flex flex-col gap-5 lg:flex-row"><TabsList className="h-auto w-full shrink-0 flex-wrap justify-start lg:w-44 lg:flex-col lg:items-stretch"><div className="w-full px-2 pb-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Analytics</div>{(["overview", "sales", "products", "customers", "inventory"] as Tab[]).map((value) => <TabsTrigger key={value} value={value} className="justify-start capitalize">{value === "sales" ? "Sales & Finance" : value}</TabsTrigger>)}</TabsList><div className="min-w-0 flex-1"><TabsContent value="overview" className="mt-0"><QueryState query={overview}><OverviewPanel data={overview.data} /></QueryState></TabsContent><TabsContent value="sales" className="mt-0"><QueryState query={overview}><SalesPanel data={overview.data} /></QueryState></TabsContent><TabsContent value="products" className="mt-0"><QueryState query={products}><ProductsPanel data={products.data} /></QueryState></TabsContent><TabsContent value="customers" className="mt-0"><QueryState query={customers}><CustomerPanel data={customers.data} /></QueryState></TabsContent><TabsContent value="inventory" className="mt-0"><QueryState query={inventory}><InventoryPanel data={inventory.data} /></QueryState></TabsContent></div></Tabs></div>
}

function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <div className="w-36"><label className="mb-1 block text-xs font-medium">{label}</label><Select value={value} onValueChange={(v) => v && onChange(v)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{options.map(([key, text]) => <SelectItem key={key} value={key}>{text}</SelectItem>)}</SelectContent></Select></div> }
function OverviewPanel({ data }: { data?: OverviewAnalytics }) { const k = data?.kpis ?? {}; const cards = [[CircleDollarSign, "Gross sales", money(k.grossSales ?? 0)], [Banknote, "Net sales", money(k.netSales ?? 0)], [ClipboardList, "Orders", (k.orders ?? 0).toLocaleString()], [ShoppingBag, "Average order value", money(k.averageOrderValue ?? 0)], [Users, "Customers", (k.customers ?? 0).toLocaleString()], [Package, "Items sold", (k.itemsSold ?? 0).toLocaleString()], [Boxes, "Discounts", money(k.discounts ?? 0)], [Group, "Outstanding", money(k.outstanding ?? 0)]] as const; return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(([icon, label, value]) => <StatCard key={label} icon={icon} label={label} value={value} />)}</div><OverviewCharts data={data} /></div> }
function OverviewCharts({ data }: { data?: OverviewAnalytics }) { return <div className="grid gap-4 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>Revenue trend</CardTitle><CardDescription>Revenue and orders by day</CardDescription></CardHeader><CardContent><div className="h-72">{data?.trend?.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data.trend}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="revenue" name="Revenue" fill="var(--chart-3)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer> : <Empty />}</div></CardContent></Card><MixCard title="Order sources" rows={data?.orderMix?.sources ?? []} value="orders" /></div> }
function SalesPanel({ data }: { data?: OverviewAnalytics }) { const k = data?.kpis ?? {}; return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Sales & finance</CardTitle><CardDescription>Financial components for this range</CardDescription></CardHeader><CardContent className="space-y-3">{[["Gross sales", k.grossSales], ["Discounts", k.discounts], ["Tax", k.tax], ["Service charge", k.serviceCharge], ["Refunds", k.refunds], ["Net sales", k.netSales], ["Outstanding", k.outstanding]].map(([label, value]) => <div key={String(label)} className="flex justify-between border-b pb-2 text-sm last:border-0"><span>{label}</span><span className="font-semibold">{money(Number(value ?? 0))}</span></div>)}</CardContent></Card><MixCard title="Payment mix" rows={data?.paymentMix ?? []} value="amount" /></div> }
function ProductsPanel({ data }: { data?: ProductsAnalytics }) { return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Top-selling foods</CardTitle><CardDescription>Quantity, revenue, orders, and contribution</CardDescription></CardHeader><CardContent className="space-y-3">{data?.foods?.length ? data.foods.slice(0, 10).map((r) => <div key={r.foodId} className="flex items-center justify-between border-b pb-2 text-sm"><span>{r.food}<small className="ml-2 text-muted-foreground">{r.quantity.toLocaleString()} sold · {r.orders} orders</small></span><span className="font-medium">{money(r.revenue)} <small className="text-muted-foreground">{r.share.toFixed(1)}%</small></span></div>) : <Empty />}</CardContent></Card><MixCard title="Category performance" rows={data?.categories ?? []} value="revenue" /></div> }
function InventoryPanel({ data }: { data?: InventoryAnalytics }) { return <div className="grid gap-4 lg:grid-cols-2"><div className="grid grid-cols-2 gap-3"><StatCard icon={CircleDollarSign} label="Inventory value" value={money(data?.kpis?.inventoryValue ?? 0)} /><StatCard icon={Boxes} label="Low-stock ingredients" value={String(data?.kpis?.lowStock ?? 0)} /><StatCard icon={Package} label="Out of stock" value={String(data?.kpis?.outOfStock ?? 0)} /><StatCard icon={ClipboardList} label="Reserved stock" value={String(data?.kpis?.reservedStock ?? 0)} /></div><MixCard title="Stock movement" rows={data?.movement ?? []} value="quantity" /></div> }
function CustomerPanel({ data }: { data?: CustomersAnalytics }) { const k = data?.kpis ?? {}; return <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard icon={Users} label="Total customers" value={String(k.totalCustomers ?? 0)} /><StatCard icon={Users} label="New customers" value={String(k.newCustomers ?? 0)} /><StatCard icon={Group} label="Repeat rate" value={`${Number(k.repeatRate ?? 0).toFixed(1)}%`} /><StatCard icon={CircleDollarSign} label="Average spend" value={money(Number(k.averageSpend ?? 0))} /></div> }
function MixCard({ title, rows, value }: { title: string; rows: Array<Record<string, string | number | null | undefined>>; value: string }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{rows.length ? rows.map((r) => <div key={String(r.name ?? r.category)} className="flex items-center justify-between border-b pb-2 text-sm last:border-0"><span className="capitalize">{String(r.name ?? r.category).replaceAll("_", " ")}</span><span className="font-medium">{typeof r[value] === "number" ? (value === "amount" || value === "revenue" ? money(r[value]) : r[value].toLocaleString()) : "—"}</span></div>) : <Empty />}</CardContent></Card> }
function Empty() { return <div className="flex min-h-32 items-center justify-center text-sm text-muted-foreground">No data for this range.</div> }
