import { BadRequestException, ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DataSource } from 'typeorm';
import { OutletAccessService, ALL_OUTLETS, AccessibleOutlets } from '../auth/outlet-access.service';
import { PermissionsService } from '../auth/permissions.service';
import { User } from '../users/entities/user.entity';
import { ASSISTANT_SYSTEM_PROMPT, ADMIN_ROLES } from './assistant.constants';

@Injectable()
export class AssistantService {
  constructor(private readonly db: DataSource, private readonly access: OutletAccessService, private readonly permissions: PermissionsService, private readonly config: ConfigService) {}
  private async assertAdmin(user: User) { if (user.isSuperadmin) return; const roles = await this.permissions.getRoleSlugs(user.id); if (![...roles].some((role) => ADMIN_ROLES.has(role))) throw new ForbiddenException('Only admins can use the operations assistant'); }
  private async ids(user: User, outletId?: number) { const outlets = await this.access.getAccessibleOutletIds(user.id, user.isSuperadmin); if (outletId !== undefined) await this.access.assertOutletAccess(user.id, user.isSuperadmin, outletId); if (outlets !== ALL_OUTLETS && outlets.length === 0) throw new ForbiddenException('You do not have access to any outlet'); return outletId === undefined && outlets === ALL_OUTLETS ? undefined : outletId === undefined ? outlets : [outletId]; }
  private async llm(question: string, context: unknown) { const key = this.config.get<string>('GROQ_API_KEY') || process.env.GROQ_API_KEY; if (!key) throw new Error('GROQ_API_KEY is not configured'); const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.GROQ_MODEL || 'qwen/qwen3.6-27b', temperature: 0.1, messages: [{ role: 'system', content: ASSISTANT_SYSTEM_PROMPT }, { role: 'user', content: `Question: ${question}\nTrusted database context:\n${JSON.stringify(context)}` }] }) }); if (!response.ok) throw new Error(`LLM request failed (${response.status})`); return ((await response.json()) as { choices: [{ message: { content: string } }] }).choices[0].message.content; }
  async chat(user: User, question: string, outletId?: number) { await this.assertAdmin(user); if (!question.trim()) throw new BadRequestException('Question is required'); const ids = await this.ids(user, outletId); const q = question.toLowerCase(); const params = ids ? [ids] : []; let route = 'DATA'; let data: unknown; if (/(why|improv|recommend|insight|trend|going wrong|sudhar)/i.test(q)) { route = 'INSIGHT'; data = await this.db.query(`SELECT summary_date, metrics, narrative FROM daily_summaries WHERE ($1::bigint[] IS NULL OR outlet_id = ANY($1)) ORDER BY summary_date DESC LIMIT 14`, [ids ?? null]); } else if (/cancel/.test(q)) data = await this.db.query(`SELECT COUNT(*)::int AS cancellations FROM reservations WHERE status='cancelled' ${ids ? 'AND outlet_id = ANY($1::bigint[])' : ''}`, params).then((rows) => rows[0]); else if (/booking|reservation/.test(q)) data = await this.db.query(`SELECT COUNT(*)::int AS bookings FROM reservations WHERE status <> 'cancelled' AND created_at >= CURRENT_DATE ${ids ? 'AND outlet_id = ANY($1::bigint[])' : ''}`, params).then((rows) => rows[0]); else data = await this.db.query(`SELECT COUNT(*)::int AS orders, COALESCE(SUM(grand_total),0)::numeric AS revenue FROM orders WHERE status <> 'cancelled' AND created_at >= CURRENT_DATE ${ids ? 'AND outlet_id = ANY($1::bigint[])' : ''}`, params).then((rows) => rows[0]); return { route, answer: await this.llm(question, data), ...(route === 'DATA' ? { data } : {}) }; }
  async dailySummary(secret?: string) { const expected = process.env.ASSISTANT_CRON_SECRET; if (!expected || secret !== expected) throw new UnauthorizedException('Invalid cron secret'); const outlets = (await this.db.query('SELECT id FROM outlets WHERE is_active = true') as Array<{ id: string }>).map((row) => Number(row.id)); const results: Array<{ outletId: number }> = []; for (const outletId of outlets) { const [metrics] = await this.db.query(`SELECT COUNT(*) FILTER (WHERE status <> 'cancelled')::int AS bookings, COUNT(*) FILTER (WHERE status = 'cancelled')::int AS cancellations, COALESCE(SUM(grand_total) FILTER (WHERE status <> 'cancelled'),0)::numeric AS revenue FROM orders WHERE outlet_id=$1 AND created_at >= CURRENT_DATE AND created_at < CURRENT_DATE + interval '1 day'`, [outletId]) as Array<Record<string, unknown>>; const narrative = await this.llm("Summarize today's performance and give concise actions.", metrics); await this.db.query(`INSERT INTO daily_summaries(outlet_id,summary_date,metrics,narrative) VALUES($1,CURRENT_DATE,$2,$3) ON CONFLICT(outlet_id,summary_date) DO UPDATE SET metrics=EXCLUDED.metrics,narrative=EXCLUDED.narrative,updated_at=now()`, [outletId, JSON.stringify({ ...metrics, occupancyRate: null, occupancyNote: 'Room inventory is not available in the current schema.' }), narrative]); results.push({ outletId }); } return { processed: results.length, results }; }
}
