import { BadRequestException, ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DataSource } from 'typeorm';
import { OutletAccessService, ALL_OUTLETS, AccessibleOutlets } from '../auth/outlet-access.service';
import { PermissionsService } from '../auth/permissions.service';
import { User } from '../users/entities/user.entity';
import { ASSISTANT_SYSTEM_PROMPT, ADMIN_ROLES } from './assistant.constants';

type Route = 'DATA' | 'INSIGHT';

@Injectable()
export class AssistantService {
  constructor(private readonly db: DataSource, private readonly access: OutletAccessService, private readonly permissions: PermissionsService, private readonly config: ConfigService) {}
  private async assertAdmin(user: User) { if (user.isSuperadmin) return; const roles = await this.permissions.getRoleSlugs(user.id); if (![...roles].some((role) => ADMIN_ROLES.has(role))) throw new ForbiddenException('Only admins can use the operations assistant'); }
  private async ids(user: User, outletId?: number): Promise<number[] | undefined> { const outlets = await this.access.getAccessibleOutletIds(user.id, user.isSuperadmin); if (outletId !== undefined) await this.access.assertOutletAccess(user.id, user.isSuperadmin, outletId); if (outlets !== ALL_OUTLETS && outlets.length === 0) throw new ForbiddenException('You do not have access to any outlet'); if (outletId !== undefined) return [outletId]; if (outlets === ALL_OUTLETS) return undefined; return outlets; }
  private async llm(question: string, context: unknown) { const key = this.config.get<string>('GROQ_API_KEY') || process.env.GROQ_API_KEY; if (!key) throw new Error('GROQ_API_KEY is not configured'); const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.GROQ_MODEL || 'qwen/qwen3.6-27b', temperature: 0.1, max_tokens: 500, messages: [{ role: 'system', content: ASSISTANT_SYSTEM_PROMPT }, { role: 'user', content: `Q: ${question}\nData: ${JSON.stringify(context)}` }] }) }); if (!response.ok) throw new Error(`LLM request failed (${response.status})`); return ((await response.json()) as { choices: [{ message: { content: string } }] }).choices[0].message.content; }
  private period(q: string) { if (/(last|past|this)\s+week|7\s*days|hafta|week/.test(q)) return 'CURRENT_DATE - INTERVAL \'6 days\''; if (/(last|past|this)\s+month|30\s*days|mahina|month/.test(q)) return 'CURRENT_DATE - INTERVAL \'29 days\''; if (/yesterday|hijo/.test(q)) return 'CURRENT_DATE - INTERVAL \'1 day\''; return 'CURRENT_DATE'; }
  private async safeData(question: string, ids?: number[]) { const q = question.toLowerCase(); const from = this.period(q); const outlet = ids ? ' AND outlet_id = ANY($1::bigint[])' : ''; const params = ids ? [ids] : []; if (/occupancy|room/.test(q)) return { unavailable: true, reason: 'Room inventory is not available in the current database schema.' }; if (/complaint|issue|grievance/.test(q)) return this.db.query(`SELECT type AS category, COUNT(*)::int AS count FROM service_requests WHERE created_at >= ${from}${ids ? ' AND outlet_id = ANY($1::bigint[])' : ''} GROUP BY type ORDER BY count DESC`, params); if (/cancel/.test(q)) return this.db.query(`SELECT COUNT(*)::int AS cancellations FROM reservations WHERE status='cancelled' AND created_at >= ${from}${ids ? ' AND outlet_id = ANY($1::bigint[])' : ''}`, params).then((rows) => rows[0]); if (/booking|reservation/.test(q)) return this.db.query(`SELECT COUNT(*)::int AS bookings FROM reservations WHERE status <> 'cancelled' AND created_at >= ${from}${ids ? ' AND outlet_id = ANY($1::bigint[])' : ''}`, params).then((rows) => rows[0]); if (/customer|guest/.test(q)) return this.db.query(`SELECT COUNT(DISTINCT customer_id)::int AS customers FROM orders WHERE status <> 'cancelled' AND customer_id IS NOT NULL AND created_at >= ${from}${outlet}`, params).then((rows) => rows[0]); if (/revenue|sales|earning|income|bikri/.test(q)) return this.db.query(`SELECT COALESCE(SUM(grand_total),0)::numeric AS revenue FROM orders WHERE status <> 'cancelled' AND created_at >= ${from}${outlet}`, params).then((rows) => rows[0]); return this.db.query(`SELECT COUNT(*)::int AS orders, COALESCE(SUM(grand_total),0)::numeric AS revenue FROM orders WHERE status <> 'cancelled' AND created_at >= ${from}${outlet}`, params).then((rows) => rows[0]); }
  async chat(user: User, question: string, outletId?: number) { await this.assertAdmin(user); if (!question.trim()) throw new BadRequestException('Question is required'); const ids = await this.ids(user, outletId); const route: Route = /(why|improv|recommend|insight|trend|going wrong|sudhar)/i.test(question) ? 'INSIGHT' : 'DATA'; const data = route === 'INSIGHT' ? await this.db.query(`SELECT summary_date, metrics FROM daily_summaries WHERE ($1::bigint[] IS NULL OR outlet_id = ANY($1)) ORDER BY summary_date DESC LIMIT 7`, [ids ?? null]) : await this.safeData(question, ids); return { route, answer: await this.llm(question, data), ...(route === 'DATA' ? { data } : {}) }; }
  async dailySummary(secret?: string) { const expected = process.env.ASSISTANT_CRON_SECRET; if (!expected || secret !== expected) throw new UnauthorizedException('Invalid cron secret'); const outlets = (await this.db.query('SELECT id FROM outlets WHERE is_active = true') as Array<{ id: string }>).map((row) => Number(row.id)); const results: Array<{ outletId: number }> = []; for (const outletId of outlets) { const [metrics] = await this.db.query(`SELECT COUNT(*) FILTER (WHERE status <> 'cancelled')::int AS bookings, COUNT(*) FILTER (WHERE status = 'cancelled')::int AS cancellations, COALESCE(SUM(grand_total) FILTER (WHERE status <> 'cancelled'),0)::numeric AS revenue FROM orders WHERE outlet_id=$1 AND created_at >= CURRENT_DATE AND created_at < CURRENT_DATE + interval '1 day'`, [outletId]) as Array<Record<string, unknown>>; const narrative = await this.llm("Summarize today's performance and give concise actions.", metrics); await this.db.query(`INSERT INTO daily_summaries(outlet_id,summary_date,metrics,narrative) VALUES($1,CURRENT_DATE,$2,$3) ON CONFLICT(outlet_id,summary_date) DO UPDATE SET metrics=EXCLUDED.metrics,narrative=EXCLUDED.narrative,updated_at=now()`, [outletId, JSON.stringify({ ...metrics, occupancyRate: null, occupancyNote: 'Room inventory is not available in the current schema.' }), narrative]); results.push({ outletId }); } return { processed: results.length, results }; }
}
