import { BadRequestException, ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DataSource } from 'typeorm';
import { OutletAccessService, ALL_OUTLETS, AccessibleOutlets } from '../auth/outlet-access.service';
import { PermissionsService } from '../auth/permissions.service';
import { User } from '../users/entities/user.entity';
import { ASSISTANT_SYSTEM_PROMPT, ADMIN_ROLES } from './assistant.constants';

type Route = 'DATA' | 'INSIGHT' | 'CHAT';
type DataIntent = 'occupancy' | 'inventory' | 'menu' | 'staffSummary' | 'payments' | 'serviceIssues' | 'cancellations' | 'bookings' | 'customers' | 'revenue' | 'orderDetails' | 'overview';
type AnalyticsPlan = { intent: DataIntent | 'conversation'; period: 'today' | 'yesterday' | 'dayBeforeYesterday' | '7d' | '30d'; groupBy?: 'day' | 'type' };

@Injectable()
export class AssistantService {
  constructor(private readonly db: DataSource, private readonly access: OutletAccessService, private readonly permissions: PermissionsService, private readonly config: ConfigService) {}
  private async assertAdmin(user: User) { if (user.isSuperadmin) return; const roles = await this.permissions.getRoleSlugs(user.id); if (![...roles].some((role) => ADMIN_ROLES.has(role))) throw new ForbiddenException('Only admins can use the operations assistant'); }
  private async ids(user: User, outletId?: number): Promise<number[] | undefined> { const outlets = await this.access.getAccessibleOutletIds(user.id, user.isSuperadmin); if (outletId !== undefined) await this.access.assertOutletAccess(user.id, user.isSuperadmin, outletId); if (outlets !== ALL_OUTLETS && outlets.length === 0) throw new ForbiddenException('You do not have access to any outlet'); if (outletId !== undefined) return [outletId]; if (outlets === ALL_OUTLETS) return undefined; return outlets; }
  private async llm(question: string, context: unknown) { const key = this.config.get<string>('GROQ_API_KEY') || process.env.GROQ_API_KEY; if (!key) throw new Error('GROQ_API_KEY is not configured'); const model = process.env.GROQ_MODEL || 'qwen/qwen3.6-27b'; const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model, temperature: 0.1, max_tokens: 700, reasoning_format: 'hidden', reasoning_effort: 'none', messages: [{ role: 'system', content: ASSISTANT_SYSTEM_PROMPT }, { role: 'user', content: `Q: ${question}\nData: ${JSON.stringify(context)}` }] }) }); if (!response.ok) throw new Error(`LLM request failed (${response.status})`); const answer = ((await response.json()) as { choices: [{ message: { content: string } }] }).choices[0].message.content; const thinkStart = answer.search(/\\?<think>/i); if (thinkStart === -1) return answer.trim(); const afterThink = answer.slice(thinkStart); const thinkEnd = afterThink.search(/\\?<\/think>/i); return (thinkEnd === -1 ? answer.slice(0, thinkStart) : answer.slice(0, thinkStart) + afterThink.slice(thinkEnd + afterThink.match(/\\?<\/think>/i)![0].length)).trim(); }
  private async plan(question: string): Promise<AnalyticsPlan | null> {
    const key = this.config.get<string>('GROQ_API_KEY') || process.env.GROQ_API_KEY;
    if (!key) return null;
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.GROQ_MODEL || 'qwen/qwen3.6-27b', temperature: 0, max_tokens: 160, reasoning_format: 'hidden', reasoning_effort: 'none', messages: [{ role: 'system', content: 'Convert the user question into JSON only. Never write SQL. Use conversation for greetings, casual chat, or questions unrelated to restaurant data. Allowed intent values: conversation, occupancy, inventory, menu, staffSummary, payments, serviceIssues, cancellations, bookings, customers, revenue, orderDetails, overview. Use inventory for stock or ingredient availability, menu for food/menu questions, staffSummary for staff counts/statuses, payments for payment totals or methods, and orderDetails for requests to list or inspect individual orders. Allowed period values: today, yesterday, dayBeforeYesterday, 7d, 30d. Allowed groupBy values: day, type. Use groupBy only when requested. Use type only for serviceIssues. Return exactly: {"intent":"...","period":"...","groupBy":"..."}.' }, { role: 'user', content: question }] }) });
    if (!response.ok) return null;
    try {
      const content = ((await response.json()) as { choices: [{ message: { content: string } }] }).choices[0].message.content;
      const parsed = JSON.parse(content.match(/\{[\s\S]*\}/)?.[0] ?? '') as Partial<AnalyticsPlan>;
      if (!['conversation', 'occupancy', 'inventory', 'menu', 'staffSummary', 'payments', 'serviceIssues', 'cancellations', 'bookings', 'customers', 'revenue', 'orderDetails', 'overview'].includes(parsed.intent ?? '') || !['today', 'yesterday', 'dayBeforeYesterday', '7d', '30d'].includes(parsed.period ?? '')) return null;
      if (parsed.groupBy !== undefined && !['day', 'type'].includes(parsed.groupBy)) return null;
      if (parsed.groupBy === 'type' && parsed.intent !== 'serviceIssues') return null;
      return { intent: parsed.intent as AnalyticsPlan['intent'], period: parsed.period as AnalyticsPlan['period'], ...(parsed.groupBy ? { groupBy: parsed.groupBy } : {}) };
    } catch { return null; }
  }
  private period(q: string) { if (/(last|past|this)\s+week|7\s*days|hafta|week/.test(q)) return { from: "CURRENT_DATE - INTERVAL '6 days'", to: "CURRENT_DATE + INTERVAL '1 day'", label: 'last 7 days', value: '7d' as const }; if (/(last|past|this)\s+month|30\s*days|mahina|month/.test(q)) return { from: "CURRENT_DATE - INTERVAL '29 days'", to: "CURRENT_DATE + INTERVAL '1 day'", label: 'last 30 days', value: '30d' as const }; if (/day before yesterday|two days ago|parsi ko hijo/.test(q)) return { from: "CURRENT_DATE - INTERVAL '2 days'", to: "CURRENT_DATE - INTERVAL '1 day'", label: 'day before yesterday', value: 'dayBeforeYesterday' as const }; if (/yesterday|hijo/.test(q)) return { from: "CURRENT_DATE - INTERVAL '1 day'", to: 'CURRENT_DATE', label: 'yesterday', value: 'yesterday' as const }; return { from: 'CURRENT_DATE', to: "CURRENT_DATE + INTERVAL '1 day'", label: 'today', value: 'today' as const }; }
  private intent(question: string): DataIntent { const q = question.toLowerCase(); if (/inventory|stock|ingredient|items?\s+(in|available)|available\s+items?/.test(q)) return 'inventory'; if (/menu|food|dish|dishes|recipe/.test(q)) return 'menu'; if (/staff|employee|employees|team member/.test(q)) return 'staffSummary'; if (/payment|payments|cash|card|refund/.test(q)) return 'payments'; if (/order\s+(detail|details|list|number)|list\s+orders|individual\s+orders|show.*orders/.test(q)) return 'orderDetails'; if (/occupancy|room/.test(q)) return 'occupancy'; if (/complaint|issue|grievance|service request/.test(q)) return 'serviceIssues'; if (/cancel/.test(q)) return 'cancellations'; if (/booking|reservation/.test(q)) return 'bookings'; if (/customer|guest/.test(q)) return 'customers'; if (/revenue|sales|earning|income|bikri/.test(q)) return 'revenue'; return 'overview'; }
  private async safeData(question: string, ids?: number[], aiPlan?: AnalyticsPlan | null) {
    const q = question.toLowerCase();
    const period = this.period(q);
    const fallbackIntent = this.intent(question);
    const selected = aiPlan ?? { intent: fallbackIntent, period: period.value };
    const intent = selected.intent;
    const selectedPeriod = selected.period === period.value ? period : selected.period === '7d' ? { from: "CURRENT_DATE - INTERVAL '6 days'", to: "CURRENT_DATE + INTERVAL '1 day'", label: 'last 7 days' } : selected.period === '30d' ? { from: "CURRENT_DATE - INTERVAL '29 days'", to: "CURRENT_DATE + INTERVAL '1 day'", label: 'last 30 days' } : selected.period === 'dayBeforeYesterday' ? { from: "CURRENT_DATE - INTERVAL '2 days'", to: "CURRENT_DATE - INTERVAL '1 day'", label: 'day before yesterday' } : selected.period === 'yesterday' ? { from: "CURRENT_DATE - INTERVAL '1 day'", to: 'CURRENT_DATE', label: 'yesterday' } : { from: 'CURRENT_DATE', to: "CURRENT_DATE + INTERVAL '1 day'", label: 'today' };
    if (intent === 'occupancy') return { intent, period: period.label, unavailable: true, reason: 'Room inventory is not available in the current database schema.' };

    const outletFilter = ids ? ' AND outlet_id = ANY($1::bigint[])' : '';
    const params = ids ? [ids] : [];
    const dateFilter = (column: string) => ` AND ${column} >= ${selectedPeriod.from} AND ${column} < ${selectedPeriod.to}`;
    const groupBy = selected.groupBy;
    let metrics: unknown;
    if (intent === 'inventory') {
      metrics = await this.db.query(`SELECT i.name, i.code, SUM(s.quantity)::numeric AS quantity, SUM(s.reserved_quantity)::numeric AS "reservedQuantity", GREATEST(SUM(s.quantity) - SUM(s.reserved_quantity), 0)::numeric AS "availableQuantity", MAX(i.reorder_level)::numeric AS "reorderLevel", MAX(i.minimum_stock)::numeric AS "minimumStock", CASE WHEN SUM(s.quantity) <= 0 THEN 'out_of_stock' WHEN SUM(s.quantity) - SUM(s.reserved_quantity) <= GREATEST(MAX(i.reorder_level), MAX(i.minimum_stock)) THEN 'low_stock' ELSE 'in_stock' END AS status FROM warehouse_ingredient_stocks s JOIN ingredients i ON i.id = s.ingredient_id JOIN warehouses w ON w.id = s.warehouse_id WHERE i.is_active = true${ids ? ' AND w.outlet_id = ANY($1::bigint[])' : ''} GROUP BY i.id, i.name, i.code ORDER BY "availableQuantity" ASC LIMIT 100`, params);
    } else if (intent === 'menu') {
      metrics = await this.db.query(`SELECT name, item_type AS type, food_type AS "foodType", is_active AS "isActive" FROM foods WHERE is_active = true ORDER BY name LIMIT 200`);
    } else if (intent === 'staffSummary') {
      metrics = await this.db.query(`SELECT employment_status AS status, COUNT(*)::int AS count FROM employees WHERE is_active = true${ids ? ' AND outlet_id = ANY($1::bigint[])' : ''} GROUP BY employment_status ORDER BY employment_status`, params);
    } else if (intent === 'payments') {
      metrics = await this.db.query(`SELECT method, type, COUNT(*)::int AS count, COALESCE(SUM(amount),0)::numeric AS amount FROM order_payments WHERE status = 'completed'${dateFilter('created_at')}${outletFilter} GROUP BY method, type ORDER BY amount DESC`, params);
    } else if (intent === 'orderDetails') {
      metrics = await this.db.query(`SELECT o.order_number AS "orderNumber", o.bill_number AS "billNumber", o.order_type AS "orderType", o.order_source AS "orderSource", o.status, o.payment_status AS "paymentStatus", o.grand_total AS "grandTotal", o.created_at AS "createdAt", COALESCE(items.items, '[]'::json) AS items FROM orders o LEFT JOIN LATERAL (SELECT json_agg(json_build_object('name', f.name, 'quantity', oi.quantity) ORDER BY f.name) AS items FROM order_items oi JOIN foods f ON f.id = oi.food_id WHERE oi.order_id = o.id) items ON true WHERE 1=1${dateFilter('o.created_at')}${ids ? ' AND o.outlet_id = ANY($1::bigint[])' : ''} ORDER BY o.created_at LIMIT 100`, params);
    } else if (intent === 'serviceIssues') {
      metrics = await this.db.query(`SELECT ${groupBy === 'day' ? "DATE_TRUNC('day', created_at)::date" : 'type AS category'}, COUNT(*)::int AS count FROM service_requests WHERE 1=1${dateFilter('created_at')}${outletFilter} GROUP BY ${groupBy === 'day' ? "DATE_TRUNC('day', created_at)" : 'type'} ORDER BY count DESC LIMIT 100`, params);
    } else if (intent === 'cancellations') {
      metrics = groupBy === 'day' ? await this.db.query(`SELECT DATE_TRUNC('day', created_at)::date AS day, COUNT(*)::int AS cancellations FROM reservations WHERE status='cancelled'${dateFilter('created_at')}${outletFilter} GROUP BY DATE_TRUNC('day', created_at) ORDER BY day`, params) : (await this.db.query(`SELECT COUNT(*)::int AS cancellations FROM reservations WHERE status='cancelled'${dateFilter('created_at')}${outletFilter}`, params))[0];
    } else if (intent === 'bookings') {
      metrics = groupBy === 'day' ? await this.db.query(`SELECT DATE_TRUNC('day', created_at)::date AS day, COUNT(*)::int AS bookings FROM reservations WHERE status <> 'cancelled'${dateFilter('created_at')}${outletFilter} GROUP BY DATE_TRUNC('day', created_at) ORDER BY day`, params) : (await this.db.query(`SELECT COUNT(*)::int AS bookings FROM reservations WHERE status <> 'cancelled'${dateFilter('created_at')}${outletFilter}`, params))[0];
    } else if (intent === 'customers') {
      metrics = (await this.db.query(`SELECT COUNT(DISTINCT customer_id)::int AS customers FROM orders WHERE status <> 'cancelled' AND customer_id IS NOT NULL${dateFilter('created_at')}${outletFilter}`, params))[0];
    } else if (intent === 'revenue') {
      metrics = groupBy === 'day' ? await this.db.query(`SELECT DATE_TRUNC('day', created_at)::date AS day, COALESCE(SUM(grand_total),0)::numeric AS revenue FROM orders WHERE status <> 'cancelled'${dateFilter('created_at')}${outletFilter} GROUP BY DATE_TRUNC('day', created_at) ORDER BY day`, params) : (await this.db.query(`SELECT COALESCE(SUM(grand_total),0)::numeric AS revenue FROM orders WHERE status <> 'cancelled'${dateFilter('created_at')}${outletFilter}`, params))[0];
    } else {
      metrics = (await this.db.query(`SELECT COUNT(*)::int AS orders, COALESCE(SUM(grand_total),0)::numeric AS revenue FROM orders WHERE status <> 'cancelled'${dateFilter('created_at')}${outletFilter}`, params))[0];
    }
    return { intent, period: selectedPeriod.label, ...(groupBy ? { groupBy } : {}), metrics };
  }
  async chat(user: User, question: string, outletId?: number) { await this.assertAdmin(user); if (!question.trim()) throw new BadRequestException('Question is required'); const ids = await this.ids(user, outletId); const fallbackIntent = this.intent(question); const plan = await this.plan(question); const selectedIntent = plan?.intent ?? fallbackIntent; const route: Route = /(why|improv|recommend|insight|trend|going wrong|sudhar)/i.test(question) ? 'INSIGHT' : selectedIntent === 'conversation' || selectedIntent === 'overview' ? 'CHAT' : 'DATA'; const data = route === 'INSIGHT' ? { intent: 'dailySummary', period: 'last 7 days', summaries: await this.db.query(`SELECT summary_date, metrics FROM daily_summaries WHERE ($1::bigint[] IS NULL OR outlet_id = ANY($1)) ORDER BY summary_date DESC LIMIT 7`, [ids ?? null]) } : route === 'DATA' ? await this.safeData(question, ids, plan) : { intent: 'conversation' }; return { route, answer: await this.llm(question, data), ...(route === 'DATA' ? { data } : {}) }; }
  async dailySummary(secret?: string) { const expected = process.env.ASSISTANT_CRON_SECRET; if (!expected || secret !== expected) throw new UnauthorizedException('Invalid cron secret'); const outlets = (await this.db.query('SELECT id FROM outlets WHERE is_active = true') as Array<{ id: string }>).map((row) => Number(row.id)); const results: Array<{ outletId: number }> = []; for (const outletId of outlets) { const [metrics] = await this.db.query(`SELECT COUNT(*) FILTER (WHERE status <> 'cancelled')::int AS bookings, COUNT(*) FILTER (WHERE status = 'cancelled')::int AS cancellations, COALESCE(SUM(grand_total) FILTER (WHERE status <> 'cancelled'),0)::numeric AS revenue FROM orders WHERE outlet_id=$1 AND created_at >= CURRENT_DATE AND created_at < CURRENT_DATE + interval '1 day'`, [outletId]) as Array<Record<string, unknown>>; const narrative = await this.llm("Summarize today's performance and give concise actions.", metrics); await this.db.query(`INSERT INTO daily_summaries(outlet_id,summary_date,metrics,narrative) VALUES($1,CURRENT_DATE,$2,$3) ON CONFLICT(outlet_id,summary_date) DO UPDATE SET metrics=EXCLUDED.metrics,narrative=EXCLUDED.narrative,updated_at=now()`, [outletId, JSON.stringify({ ...metrics, occupancyRate: null, occupancyNote: 'Room inventory is not available in the current schema.' }), narrative]); results.push({ outletId }); } return { processed: results.length, results }; }
}
