"use client"

import { useState } from "react"
import { Button } from "@rms/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@rms/ui/card"
import { Input } from "@rms/ui/input"
import { apiClient } from "@rms/api-client/client"

type ChatResult = { route: string; answer: string }

export function AssistantPanel() {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState<ChatResult | null>(null); const [outletId, setOutletId] = useState(""); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("")
  async function ask() { if (!question.trim()) return; setBusy(true); setMessage(""); try { setAnswer(await apiClient<ChatResult>("/assistant/chat", { method: "POST", body: JSON.stringify({ question, outletId: outletId ? Number(outletId) : undefined }) })) } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to answer the question") } finally { setBusy(false) } }
  async function upload() { if (!file || !outletId) { setMessage("Select an outlet ID and document before uploading"); return }; setBusy(true); setMessage(""); try { const data = new FormData(); data.append("file", file); data.append("outletId", outletId); const response = await fetch("/api/backend/assistant/ingest", { method: "POST", body: data }); if (!response.ok) throw new Error((await response.text()) || "Upload failed"); setMessage("Document indexed successfully"); setFile(null) } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed") } finally { setBusy(false) } }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Operations Assistant</h1><p className="text-sm text-muted-foreground">Ask about hotel documents and aggregate performance. Available to admins only.</p></div><Card><CardHeader><CardTitle>Ask a question</CardTitle><CardDescription>English, Romanized Nepali, or mixed language is supported.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void ask() }} placeholder="e.g. aaja kati booking vayo?" /><Button onClick={() => void ask()} disabled={busy}>Ask</Button></div>{answer && <div className="rounded-lg bg-muted p-4 text-sm whitespace-pre-wrap"><div className="mb-2 text-xs font-medium uppercase text-muted-foreground">{answer.route}</div>{answer.answer}</div>}</CardContent></Card><Card><CardHeader><CardTitle>Index a policy or SOP</CardTitle><CardDescription>PDF and DOCX files are chunked and embedded without guest PII.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-center gap-2"><Input className="max-w-44" value={outletId} onChange={(event) => setOutletId(event.target.value)} placeholder="Outlet ID" /><Input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><Button variant="outline" onClick={() => void upload()} disabled={busy}>Upload and index</Button></CardContent></Card>{message && <p className="text-sm text-muted-foreground">{message}</p>}</div>
}
