/**
 * TanStack Query key factory. Convention for this and all future CRUD
 * domains: `all` -> `lists()` -> `list(params)`, and `all` -> `detail(id)`.
 */
export const queryKeys = {
  users: {
    all: ["users"] as const,
    lists: () => [...queryKeys.users.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.users.lists(), params] as const,
    detail: (id: number) => [...queryKeys.users.all, "detail", id] as const,
    roleAssignments: (id: number) => [...queryKeys.users.all, "role-assignments", id] as const,
  },
  roles: {
    all: ["roles"] as const,
    lists: () => [...queryKeys.roles.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.roles.lists(), params] as const,
    detail: (id: number) => [...queryKeys.roles.all, "detail", id] as const,
  },
  permissions: {
    all: ["permissions"] as const,
    list: () => [...queryKeys.permissions.all, "list"] as const,
  },
  customers: {
    all: ["customers"] as const,
    lists: () => [...queryKeys.customers.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.customers.lists(), params] as const,
    detail: (id: number) => [...queryKeys.customers.all, "detail", id] as const,
    outlets: (id: number) => [...queryKeys.customers.all, "outlets", id] as const,
  },
  reservations: {
    all: ["reservations"] as const,
    lists: () => [...queryKeys.reservations.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.reservations.lists(), params] as const,
    detail: (id: number) => [...queryKeys.reservations.all, "detail", id] as const,
    tables: (id: number) => [...queryKeys.reservations.all, "tables", id] as const,
  },
  outlets: {
    all: ["outlets"] as const,
    lists: () => [...queryKeys.outlets.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.outlets.lists(), params] as const,
    detail: (id: number) => [...queryKeys.outlets.all, "detail", id] as const,
    assigned: () => [...queryKeys.outlets.all, "assigned"] as const,
  },
  outletDepartments: {
    all: ["outlet-departments"] as const,
    lists: () => [...queryKeys.outletDepartments.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.outletDepartments.lists(), params] as const,
    detail: (id: number) => [...queryKeys.outletDepartments.all, "detail", id] as const,
    assigned: (outletId: number | null) =>
      [...queryKeys.outletDepartments.all, "assigned", outletId] as const,
  },
  warehouses: {
    all: ["warehouses"] as const,
    lists: () => [...queryKeys.warehouses.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.warehouses.lists(), params] as const,
    detail: (id: number) => [...queryKeys.warehouses.all, "detail", id] as const,
  },
  foodCategories: {
    all: ["food-categories"] as const,
    lists: () => [...queryKeys.foodCategories.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.foodCategories.lists(), params] as const,
    detail: (id: number) => [...queryKeys.foodCategories.all, "detail", id] as const,
  },
  addonGroups: {
    all: ["addon-groups"] as const,
    lists: () => [...queryKeys.addonGroups.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.addonGroups.lists(), params] as const,
    detail: (id: number) => [...queryKeys.addonGroups.all, "detail", id] as const,
  },
  foods: {
    all: ["foods"] as const,
    lists: () => [...queryKeys.foods.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.foods.lists(), params] as const,
    detail: (id: number) => [...queryKeys.foods.all, "detail", id] as const,
    outlets: (id: number) => [...queryKeys.foods.all, "outlets", id] as const,
    addonGroups: (id: number) => [...queryKeys.foods.all, "addon-groups", id] as const,
    recipes: (id: number) => [...queryKeys.foods.all, "recipes", id] as const,
  },
  foodVariants: {
    all: ["food-variants"] as const,
    lists: () => [...queryKeys.foodVariants.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.foodVariants.lists(), params] as const,
    detail: (id: number) => [...queryKeys.foodVariants.all, "detail", id] as const,
    outlets: (id: number) => [...queryKeys.foodVariants.all, "outlets", id] as const,
  },
  addons: {
    all: ["addons"] as const,
    lists: () => [...queryKeys.addons.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.addons.lists(), params] as const,
    detail: (id: number) => [...queryKeys.addons.all, "detail", id] as const,
    recipes: (id: number) => [...queryKeys.addons.all, "recipes", id] as const,
  },
  diningAreas: {
    all: ["dining-areas"] as const,
    lists: () => [...queryKeys.diningAreas.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.diningAreas.lists(), params] as const,
    detail: (id: number) => [...queryKeys.diningAreas.all, "detail", id] as const,
  },
  diningTables: {
    all: ["dining-tables"] as const,
    lists: () => [...queryKeys.diningTables.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.diningTables.lists(), params] as const,
    detail: (id: number) => [...queryKeys.diningTables.all, "detail", id] as const,
  },
  tableSessions: {
    all: ["table-sessions"] as const,
    lists: () => [...queryKeys.tableSessions.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.tableSessions.lists(), params] as const,
    detail: (id: number) => [...queryKeys.tableSessions.all, "detail", id] as const,
  },
  orders: {
    all: ["orders"] as const,
    lists: () => [...queryKeys.orders.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.orders.lists(), params] as const,
    detail: (id: number) => [...queryKeys.orders.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.orders.all, "items", id] as const,
    payments: (id: number) => [...queryKeys.orders.all, "payments", id] as const,
    statusHistory: (id: number) => [...queryKeys.orders.all, "status-history", id] as const,
  },
  orderItems: {
    all: ["order-items"] as const,
    addons: (id: number) => [...queryKeys.orderItems.all, "addons", id] as const,
    reservations: (id: number) => [...queryKeys.orderItems.all, "reservations", id] as const,
  },
  kitchenTickets: {
    all: ["kitchen-tickets"] as const,
    lists: () => [...queryKeys.kitchenTickets.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.kitchenTickets.lists(), params] as const,
    detail: (id: number) => [...queryKeys.kitchenTickets.all, "detail", id] as const,
    bootstrap: (outletId: number | null) => [...queryKeys.kitchenTickets.all, "bootstrap", outletId] as const,
  },
  dashboard: {
    all: ["dashboard"] as const,
    stats: (params?: unknown) => [...queryKeys.dashboard.all, "stats", params] as const,
    charts: (params?: unknown) => [...queryKeys.dashboard.all, "charts", params] as const,
    breakdown: (params?: unknown) => [...queryKeys.dashboard.all, "breakdown", params] as const,
    inventoryActivity: (params?: unknown) => [...queryKeys.dashboard.all, "inventory-activity", params] as const,
  },
  reports: {
    all: ["reports"] as const,
    detail: (type: string, params?: unknown) => [...queryKeys.reports.all, type, params] as const,
  },
  notifications: {
    all: ["notifications"] as const,
    list: (params?: unknown) => [...queryKeys.notifications.all, "list", params] as const,
    unreadCount: (outletId: number | null) =>
      [...queryKeys.notifications.all, "unread-count", outletId] as const,
    preferences: () => [...queryKeys.notifications.all, "preferences"] as const,
    pushPublicKey: () => [...queryKeys.notifications.all, "push-public-key"] as const,
  },
  serviceRequests: {
    all: ["service-requests"] as const,
    lists: () => [...queryKeys.serviceRequests.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.serviceRequests.lists(), params] as const,
  },
  units: {
    all: ["units"] as const,
    lists: () => [...queryKeys.units.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.units.lists(), params] as const,
    detail: (id: number) => [...queryKeys.units.all, "detail", id] as const,
    conversions: (id: number) => [...queryKeys.units.all, "conversions", id] as const,
  },
  ingredientCategories: {
    all: ["ingredient-categories"] as const,
    lists: () => [...queryKeys.ingredientCategories.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.ingredientCategories.lists(), params] as const,
    detail: (id: number) => [...queryKeys.ingredientCategories.all, "detail", id] as const,
  },
  ingredients: {
    all: ["ingredients"] as const,
    lists: () => [...queryKeys.ingredients.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.ingredients.lists(), params] as const,
    detail: (id: number) => [...queryKeys.ingredients.all, "detail", id] as const,
  },
  warehouseIngredientStocks: {
    all: ["warehouse-ingredient-stocks"] as const,
    list: (params?: unknown) => [...queryKeys.warehouseIngredientStocks.all, "list", params] as const,
  },
  inventoryTransactions: {
    all: ["inventory-transactions"] as const,
    list: (params?: unknown) => [...queryKeys.inventoryTransactions.all, "list", params] as const,
  },
  stockIns: {
    all: ["stock-ins"] as const,
    lists: () => [...queryKeys.stockIns.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockIns.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockIns.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockIns.all, "items", id] as const,
  },
  stockOuts: {
    all: ["stock-outs"] as const,
    lists: () => [...queryKeys.stockOuts.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockOuts.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockOuts.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockOuts.all, "items", id] as const,
  },
  stockTransfers: {
    all: ["stock-transfers"] as const,
    lists: () => [...queryKeys.stockTransfers.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockTransfers.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockTransfers.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockTransfers.all, "items", id] as const,
  },
  ingredientWastages: {
    all: ["ingredient-wastages"] as const,
    lists: () => [...queryKeys.ingredientWastages.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.ingredientWastages.lists(), params] as const,
    detail: (id: number) => [...queryKeys.ingredientWastages.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.ingredientWastages.all, "items", id] as const,
  },
  stockAdjustments: {
    all: ["stock-adjustments"] as const,
    lists: () => [...queryKeys.stockAdjustments.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockAdjustments.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockAdjustments.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockAdjustments.all, "items", id] as const,
  },
  stockCounts: {
    all: ["stock-counts"] as const,
    lists: () => [...queryKeys.stockCounts.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockCounts.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockCounts.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockCounts.all, "items", id] as const,
  },
  supplierCategories: {
    all: ["supplier-categories"] as const,
    list: () => [...queryKeys.supplierCategories.all, "list"] as const,
  },
  suppliers: {
    all: ["suppliers"] as const,
    lists: () => [...queryKeys.suppliers.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.suppliers.lists(), params] as const,
    detail: (id: number) => [...queryKeys.suppliers.all, "detail", id] as const,
  },
  purchaseOrders: {
    all: ["purchase-orders"] as const,
    lists: () => [...queryKeys.purchaseOrders.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.purchaseOrders.lists(), params] as const,
    detail: (id: number) => [...queryKeys.purchaseOrders.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.purchaseOrders.all, "items", id] as const,
  },
  goodsReceiving: {
    all: ["goods-receiving"] as const,
    lists: () => [...queryKeys.goodsReceiving.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.goodsReceiving.lists(), params] as const,
    detail: (id: number) => [...queryKeys.goodsReceiving.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.goodsReceiving.all, "items", id] as const,
  },
  purchaseReturns: {
    all: ["purchase-returns"] as const,
    lists: () => [...queryKeys.purchaseReturns.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.purchaseReturns.lists(), params] as const,
    detail: (id: number) => [...queryKeys.purchaseReturns.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.purchaseReturns.all, "items", id] as const,
  },
  supplierPayments: {
    all: ["supplier-payments"] as const,
    lists: () => [...queryKeys.supplierPayments.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.supplierPayments.lists(), params] as const,
    detail: (id: number) => [...queryKeys.supplierPayments.all, "detail", id] as const,
  },
  positions: {
    all: ["positions"] as const,
    list: () => [...queryKeys.positions.all, "list"] as const,
  },
  employees: {
    all: ["employees"] as const,
    lists: () => [...queryKeys.employees.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.employees.lists(), params] as const,
    detail: (id: number) => [...queryKeys.employees.all, "detail", id] as const,
    performance: (id: number, params?: unknown) => [...queryKeys.employees.all, "performance", id, params] as const,
  },
  shifts: {
    all: ["shifts"] as const,
    lists: () => [...queryKeys.shifts.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.shifts.lists(), params] as const,
    detail: (id: number) => [...queryKeys.shifts.all, "detail", id] as const,
    assignments: (id: number, date?: string) => [...queryKeys.shifts.all, "assignments", id, date] as const,
  },
  attendance: {
    all: ["attendance"] as const,
    lists: () => [...queryKeys.attendance.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.attendance.lists(), params] as const,
    today: (outletId?: number) => [...queryKeys.attendance.all, "today", outletId] as const,
  },
  assignments: {
    all: ["assignments"] as const,
    tables: (outletId?: number) => [...queryKeys.assignments.all, "tables", outletId] as const,
    orders: (outletId?: number) => [...queryKeys.assignments.all, "orders", outletId] as const,
    staffDashboard: (outletId?: number) => [...queryKeys.assignments.all, "staff-dashboard", outletId] as const,
  },
  settings: {
    all: ["settings"] as const,
    category: (category: string) => [...queryKeys.settings.all, category] as const,
    allCategories: () => [...queryKeys.settings.all, "all-categories"] as const,
  },
  auditLogs: {
    all: ["audit-logs"] as const,
    list: (params?: unknown) => [...queryKeys.auditLogs.all, "list", params] as const,
  },
  loyalty: {
    all: ["loyalty"] as const,
    accounts: (params?: unknown) => [...queryKeys.loyalty.all, "accounts", params] as const,
    account: (customerId: number) => [...queryKeys.loyalty.all, "account", customerId] as const,
    transactions: (params?: unknown) => [...queryKeys.loyalty.all, "transactions", params] as const,
  },
  customerCredit: {
    all: ["customer-credit"] as const,
    accounts: (params?: unknown) => [...queryKeys.customerCredit.all, "accounts", params] as const,
    account: (customerId: number) => [...queryKeys.customerCredit.all, "account", customerId] as const,
    transactions: (params?: unknown) => [...queryKeys.customerCredit.all, "transactions", params] as const,
  },
  customerPortal: {
    all: ["customer-portal"] as const,
    profile: () => [...queryKeys.customerPortal.all, "profile"] as const,
    addresses: () => [...queryKeys.customerPortal.all, "addresses"] as const,
    orders: (params?: unknown) => [...queryKeys.customerPortal.all, "orders", params] as const,
    loyalty: () => [...queryKeys.customerPortal.all, "loyalty"] as const,
    loyaltyHistory: (params?: unknown) => [...queryKeys.customerPortal.all, "loyalty-history", params] as const,
  },
  guestMenu: {
    all: ["guest-menu"] as const,
    categories: (params?: unknown) => [...queryKeys.guestMenu.all, "categories", params] as const,
    foods: (params?: unknown) => [...queryKeys.guestMenu.all, "foods", params] as const,
    variants: (foodId?: number) => [...queryKeys.guestMenu.all, "variants", foodId] as const,
  },
  guestOrders: {
    all: ["guest-orders"] as const,
    mine: (tableCode: string) => [...queryKeys.guestOrders.all, "mine", tableCode] as const,
  },
} as const;
