/**
 * TanStack Query key factory. Convention for this and all future CRUD
 * domains: `all` -> `lists()` -> `list(params)`, and `all` -> `detail(id)`.
 */
export const queryKeys = {
  users: {
    all: ["users"] as const,
    lists: () => [...queryKeys.users.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.users.lists(), params] as const,
    detail: (id: number) => [...queryKeys.users.all, "detail", id] as const,
    roleAssignments: (id: number) => [...queryKeys.users.all, "role-assignments", id] as const,
  },
  roles: {
    all: ["roles"] as const,
    lists: () => [...queryKeys.roles.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.roles.lists(), params] as const,
    detail: (id: number) => [...queryKeys.roles.all, "detail", id] as const,
  },
  permissions: {
    all: ["permissions"] as const,
    list: () => [...queryKeys.permissions.all, "list"] as const,
  },
  outlets: {
    all: ["outlets"] as const,
    lists: () => [...queryKeys.outlets.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.outlets.lists(), params] as const,
    detail: (id: number) => [...queryKeys.outlets.all, "detail", id] as const,
  },
  outletDepartments: {
    all: ["outlet-departments"] as const,
    lists: () => [...queryKeys.outletDepartments.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.outletDepartments.lists(), params] as const,
    detail: (id: number) => [...queryKeys.outletDepartments.all, "detail", id] as const,
  },
  warehouses: {
    all: ["warehouses"] as const,
    lists: () => [...queryKeys.warehouses.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.warehouses.lists(), params] as const,
    detail: (id: number) => [...queryKeys.warehouses.all, "detail", id] as const,
  },
  foodCategories: {
    all: ["food-categories"] as const,
    lists: () => [...queryKeys.foodCategories.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.foodCategories.lists(), params] as const,
    detail: (id: number) => [...queryKeys.foodCategories.all, "detail", id] as const,
  },
  addonGroups: {
    all: ["addon-groups"] as const,
    lists: () => [...queryKeys.addonGroups.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.addonGroups.lists(), params] as const,
    detail: (id: number) => [...queryKeys.addonGroups.all, "detail", id] as const,
  },
  foods: {
    all: ["foods"] as const,
    lists: () => [...queryKeys.foods.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.foods.lists(), params] as const,
    detail: (id: number) => [...queryKeys.foods.all, "detail", id] as const,
    outlets: (id: number) => [...queryKeys.foods.all, "outlets", id] as const,
    addonGroups: (id: number) => [...queryKeys.foods.all, "addon-groups", id] as const,
  },
  foodVariants: {
    all: ["food-variants"] as const,
    lists: () => [...queryKeys.foodVariants.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.foodVariants.lists(), params] as const,
    detail: (id: number) => [...queryKeys.foodVariants.all, "detail", id] as const,
    outlets: (id: number) => [...queryKeys.foodVariants.all, "outlets", id] as const,
  },
  addons: {
    all: ["addons"] as const,
    lists: () => [...queryKeys.addons.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.addons.lists(), params] as const,
    detail: (id: number) => [...queryKeys.addons.all, "detail", id] as const,
  },
  diningAreas: {
    all: ["dining-areas"] as const,
    lists: () => [...queryKeys.diningAreas.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.diningAreas.lists(), params] as const,
    detail: (id: number) => [...queryKeys.diningAreas.all, "detail", id] as const,
  },
  diningTables: {
    all: ["dining-tables"] as const,
    lists: () => [...queryKeys.diningTables.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.diningTables.lists(), params] as const,
    detail: (id: number) => [...queryKeys.diningTables.all, "detail", id] as const,
  },
  tableSessions: {
    all: ["table-sessions"] as const,
    lists: () => [...queryKeys.tableSessions.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.tableSessions.lists(), params] as const,
    detail: (id: number) => [...queryKeys.tableSessions.all, "detail", id] as const,
  },
  orders: {
    all: ["orders"] as const,
    lists: () => [...queryKeys.orders.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.orders.lists(), params] as const,
    detail: (id: number) => [...queryKeys.orders.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.orders.all, "items", id] as const,
    tables: (id: number) => [...queryKeys.orders.all, "tables", id] as const,
    payments: (id: number) => [...queryKeys.orders.all, "payments", id] as const,
  },
  orderItems: {
    all: ["order-items"] as const,
    addons: (id: number) => [...queryKeys.orderItems.all, "addons", id] as const,
  },
  units: {
    all: ["units"] as const,
    lists: () => [...queryKeys.units.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.units.lists(), params] as const,
    detail: (id: number) => [...queryKeys.units.all, "detail", id] as const,
    conversions: (id: number) => [...queryKeys.units.all, "conversions", id] as const,
  },
  ingredientCategories: {
    all: ["ingredient-categories"] as const,
    lists: () => [...queryKeys.ingredientCategories.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.ingredientCategories.lists(), params] as const,
    detail: (id: number) => [...queryKeys.ingredientCategories.all, "detail", id] as const,
  },
  ingredients: {
    all: ["ingredients"] as const,
    lists: () => [...queryKeys.ingredients.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.ingredients.lists(), params] as const,
    detail: (id: number) => [...queryKeys.ingredients.all, "detail", id] as const,
  },
  warehouseIngredientStocks: {
    all: ["warehouse-ingredient-stocks"] as const,
    list: (params?: unknown) => [...queryKeys.warehouseIngredientStocks.all, "list", params] as const,
  },
  inventoryTransactions: {
    all: ["inventory-transactions"] as const,
    list: (params?: unknown) => [...queryKeys.inventoryTransactions.all, "list", params] as const,
  },
  stockIns: {
    all: ["stock-ins"] as const,
    lists: () => [...queryKeys.stockIns.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockIns.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockIns.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockIns.all, "items", id] as const,
  },
  stockOuts: {
    all: ["stock-outs"] as const,
    lists: () => [...queryKeys.stockOuts.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockOuts.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockOuts.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockOuts.all, "items", id] as const,
  },
  stockTransfers: {
    all: ["stock-transfers"] as const,
    lists: () => [...queryKeys.stockTransfers.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockTransfers.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockTransfers.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockTransfers.all, "items", id] as const,
  },
  ingredientWastages: {
    all: ["ingredient-wastages"] as const,
    lists: () => [...queryKeys.ingredientWastages.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.ingredientWastages.lists(), params] as const,
    detail: (id: number) => [...queryKeys.ingredientWastages.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.ingredientWastages.all, "items", id] as const,
  },
  stockAdjustments: {
    all: ["stock-adjustments"] as const,
    lists: () => [...queryKeys.stockAdjustments.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockAdjustments.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockAdjustments.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockAdjustments.all, "items", id] as const,
  },
  stockCounts: {
    all: ["stock-counts"] as const,
    lists: () => [...queryKeys.stockCounts.all, "list"] as const,
    list: (params?: unknown) => [...queryKeys.stockCounts.lists(), params] as const,
    detail: (id: number) => [...queryKeys.stockCounts.all, "detail", id] as const,
    items: (id: number) => [...queryKeys.stockCounts.all, "items", id] as const,
  },
} as const;
